name: Resize assets

on:
  push:
    branches: [ "main" ]
    paths:
      - assets/**
      - .github/workflows/resize_assets.yaml
      - resize_assets.py

jobs:
  resize-assets:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install Dependencies
      run: python -m pip install --upgrade pillow
      shell: bash
    - name: Image Resizer Action Script
      run: |
        python resize_assets.py
      shell: bash
    - name: Commit and push assets
      run: |
        git config --global http.postBuffer 157286400
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Push variants" -a
        git push
